### ISSUE TITLE
conda environment

### ISSUE THREAD

**Issue by jaysonjeg** [embodied-computation-group/metadpy#11]
Is there a conda environment file, or can you provide any further details on suitable package versions, or python version you used?. I'm having trouble making a conda environment that works without error (including for Bayesian models).

**Comment by LegrandNico** [comment]
Hi @jaysonjeg , I have just added an `environment.yml` file at the root of the package directory. All the tests are passing on my side on Linux, let me know if this is fixing the errors for you.
